jobs:
  build:
    docker:
      - image: base/archlinux
    steps:
      - prep
      - run:
          name: Update package cache
          command: pacman -Syu --noconfirm
      - run:
          name: Print the Current Time
          command: date
          
