jobs:
  build:
    docker:
      - image: base/archlinux:latest
    steps:
      - checkout
      - run:
          name: Setup system
          command: bash setup_system.sh
      - run:
          name: install package
          command: sudo -u build ./build_package.sh
      - run:
          name: Print the Current Time
          command: date
